# title: Abhijit Biswas - Game Programmer
# description: Portfolio and resume of Abhijit Biswas, a skilled game programmer with experience in C/C++, C#, Unity, and more.
theme: minima
author: Abhijit Biswas
email: gamdev.abhijit@gmail.com
github_username: gamdevAbhi
linkedin_username: linkedin.com/in/abhijit-biswas-dev/
baseurl: ""
url: "https://gamedevabhi.github.io"